/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.chart.excel.gui;

import org.chart.excel.BoletimGenerator;
import org.chart.excel.utils.FileSelector;

import javax.swing.*;
import java.util.Objects;

/**
 * @author Matheus Leffa Hilbert
 */
public class MainMenu extends javax.swing.JFrame {

    private final BoletimGenerator boletimGenerator = new BoletimGenerator();
    private String filePath;
    private String seguradora;


    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelBoletimOrigem = new javax.swing.JLabel();
        txtBoletimOrigemPath = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        labelSeguradora = new javax.swing.JLabel();
        cbxSeguradora = new javax.swing.JComboBox<>();
        btnAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boletim de Incidentes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitulo.setText("Boletim de Incidentes");

        labelBoletimOrigem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBoletimOrigem.setText("Boletim origem:");

        txtBoletimOrigemPath.setEditable(false);
        txtBoletimOrigemPath.setToolTipText("");
        txtBoletimOrigemPath.setAutoscrolls(false);

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        labelSeguradora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSeguradora.setText("Seguradora:");

        cbxSeguradora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxSeguradora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Agristamp", "Allianz", "Bradesco", "Fairfax", "HDI", "Icatu", "Liberty", "Mapfre", "Mitsui", "Porto", "Quiver", "Tokio Marine" }));
        cbxSeguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeguradoraActionPerformed(evt);
            }
        });

        btnAvancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSeguradora)
                        .addGap(6, 6, 6)
                        .addComponent(cbxSeguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelBoletimOrigem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtBoletimOrigemPath, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(160, 160, 160))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBoletimOrigem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBoletimOrigemPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelSeguradora))
                    .addComponent(cbxSeguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAvancar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        filePath = FileSelector.getFilePath();
        txtBoletimOrigemPath.setText(filePath);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cbxSeguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeguradoraActionPerformed
        seguradora = Objects.requireNonNull(cbxSeguradora.getSelectedItem()).toString();
    }//GEN-LAST:event_cbxSeguradoraActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        if (txtBoletimOrigemPath.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não foi selecionado o arquivo do boletim!", "Erro", JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException("Não foi selecionado o arquivo do boletim!");
        }
        boletimGenerator.setFilePath(filePath);
        boletimGenerator.setSeguradora(seguradora);
        boletimGenerator.generateBoletim();
        this.dispose();
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmation = JOptionPane.showConfirmDialog(this, "Tem certeza que quer finalizar o programa?", "Quer sair?", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxSeguradora;
    private javax.swing.JLabel labelBoletimOrigem;
    private javax.swing.JLabel labelSeguradora;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtBoletimOrigemPath;
    // End of variables declaration//GEN-END:variables
}
